# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grafica.ui'
#
# Created: Thu Jun 25 13:58:13 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from logic import *
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog, tabella):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(565, 450)
        self.gridLayoutWidget = QtGui.QWidget(Dialog)
        self.gridLayoutWidget.keyPressEvent
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 411, 367))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        #spazio tra le label zero - voglio che siano attaccate
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.l115 = QtGui.QLabel(self.gridLayoutWidget)
        self.l115.setObjectName(_fromUtf8("l115"))
        self.gridLayout.addWidget(self.l115, 11, 5, 1, 1)
        self.l114 = QtGui.QLabel(self.gridLayoutWidget)
        self.l114.setObjectName(_fromUtf8("l114"))
        self.gridLayout.addWidget(self.l114, 11, 4, 1, 1)
        self.l19 = QtGui.QLabel(self.gridLayoutWidget)
        self.l19.setObjectName(_fromUtf8("l19"))
        self.gridLayout.addWidget(self.l19, 1, 9, 1, 1)
        self.l54 = QtGui.QLabel(self.gridLayoutWidget)
        self.l54.setObjectName(_fromUtf8("l54"))
        self.gridLayout.addWidget(self.l54, 5, 4, 1, 1)
        self.l112 = QtGui.QLabel(self.gridLayoutWidget)
        self.l112.setObjectName(_fromUtf8("l112"))
        self.gridLayout.addWidget(self.l112, 11, 2, 1, 1)
        self.l101 = QtGui.QLabel(self.gridLayoutWidget)
        self.l101.setObjectName(_fromUtf8("l101"))
        self.gridLayout.addWidget(self.l101, 10, 1, 1, 1)
        self.l67 = QtGui.QLabel(self.gridLayoutWidget)
        self.l67.setObjectName(_fromUtf8("l67"))
        self.gridLayout.addWidget(self.l67, 6, 7, 1, 1)
        self.l113 = QtGui.QLabel(self.gridLayoutWidget)
        self.l113.setObjectName(_fromUtf8("l113"))
        self.gridLayout.addWidget(self.l113, 11, 3, 1, 1)
        self.l111 = QtGui.QLabel(self.gridLayoutWidget)
        self.l111.setObjectName(_fromUtf8("l111"))
        self.gridLayout.addWidget(self.l111, 11, 1, 1, 1)
        self.l59 = QtGui.QLabel(self.gridLayoutWidget)
        self.l59.setObjectName(_fromUtf8("l59"))
        self.gridLayout.addWidget(self.l59, 5, 9, 1, 1)
        self.l9 = QtGui.QLabel(self.gridLayoutWidget)
        self.l9.setObjectName(_fromUtf8("l9"))
        self.gridLayout.addWidget(self.l9, 0, 9, 1, 1)
        self.l34 = QtGui.QLabel(self.gridLayoutWidget)
        self.l34.setObjectName(_fromUtf8("l34"))
        self.gridLayout.addWidget(self.l34, 3, 4, 1, 1)
        self.l44 = QtGui.QLabel(self.gridLayoutWidget)
        self.l44.setObjectName(_fromUtf8("l44"))
        self.gridLayout.addWidget(self.l44, 4, 4, 1, 1)
        self.l72 = QtGui.QLabel(self.gridLayoutWidget)
        self.l72.setObjectName(_fromUtf8("l72"))
        self.gridLayout.addWidget(self.l72, 7, 2, 1, 1)
        self.l119 = QtGui.QLabel(self.gridLayoutWidget)
        self.l119.setObjectName(_fromUtf8("l119"))
        self.gridLayout.addWidget(self.l119, 11, 9, 1, 1)
        self.l55 = QtGui.QLabel(self.gridLayoutWidget)
        self.l55.setObjectName(_fromUtf8("l55"))
        self.gridLayout.addWidget(self.l55, 5, 5, 1, 1)
        self.l75 = QtGui.QLabel(self.gridLayoutWidget)
        self.l75.setObjectName(_fromUtf8("l75"))
        self.gridLayout.addWidget(self.l75, 7, 5, 1, 1)
        self.l35 = QtGui.QLabel(self.gridLayoutWidget)
        self.l35.setObjectName(_fromUtf8("l35"))
        self.gridLayout.addWidget(self.l35, 3, 5, 1, 1)
        self.l93 = QtGui.QLabel(self.gridLayoutWidget)
        self.l93.setObjectName(_fromUtf8("l93"))
        self.gridLayout.addWidget(self.l93, 9, 3, 1, 1)
        self.l24 = QtGui.QLabel(self.gridLayoutWidget)
        self.l24.setObjectName(_fromUtf8("l24"))
        self.gridLayout.addWidget(self.l24, 2, 4, 1, 1)
        self.l74 = QtGui.QLabel(self.gridLayoutWidget)
        self.l74.setObjectName(_fromUtf8("l74"))
        self.gridLayout.addWidget(self.l74, 7, 4, 1, 1)
        self.l78 = QtGui.QLabel(self.gridLayoutWidget)
        self.l78.setObjectName(_fromUtf8("l78"))
        self.gridLayout.addWidget(self.l78, 7, 8, 1, 1)
        self.l86 = QtGui.QLabel(self.gridLayoutWidget)
        self.l86.setObjectName(_fromUtf8("l86"))
        self.gridLayout.addWidget(self.l86, 8, 6, 1, 1)
        self.l71 = QtGui.QLabel(self.gridLayoutWidget)
        self.l71.setObjectName(_fromUtf8("l71"))
        self.gridLayout.addWidget(self.l71, 7, 1, 1, 1)
        self.l61 = QtGui.QLabel(self.gridLayoutWidget)
        self.l61.setObjectName(_fromUtf8("l61"))
        self.gridLayout.addWidget(self.l61, 6, 1, 1, 1)
        self.l110 = QtGui.QLabel(self.gridLayoutWidget)
        self.l110.setObjectName(_fromUtf8("l110"))
        self.gridLayout.addWidget(self.l110, 11, 0, 1, 1)
        self.l73 = QtGui.QLabel(self.gridLayoutWidget)
        self.l73.setObjectName(_fromUtf8("l73"))
        self.gridLayout.addWidget(self.l73, 7, 3, 1, 1)
        self.l100 = QtGui.QLabel(self.gridLayoutWidget)
        self.l100.setObjectName(_fromUtf8("l100"))
        self.gridLayout.addWidget(self.l100, 10, 0, 1, 1)
        self.l81 = QtGui.QLabel(self.gridLayoutWidget)
        self.l81.setObjectName(_fromUtf8("l81"))
        self.gridLayout.addWidget(self.l81, 8, 1, 1, 1)
        self.l83 = QtGui.QLabel(self.gridLayoutWidget)
        self.l83.setObjectName(_fromUtf8("l83"))
        self.gridLayout.addWidget(self.l83, 8, 3, 1, 1)
        self.l53 = QtGui.QLabel(self.gridLayoutWidget)
        self.l53.setObjectName(_fromUtf8("l53"))
        self.gridLayout.addWidget(self.l53, 5, 3, 1, 1)
        self.l82 = QtGui.QLabel(self.gridLayoutWidget)
        self.l82.setObjectName(_fromUtf8("l82"))
        self.gridLayout.addWidget(self.l82, 8, 2, 1, 1)
        self.l102 = QtGui.QLabel(self.gridLayoutWidget)
        self.l102.setObjectName(_fromUtf8("l102"))
        self.gridLayout.addWidget(self.l102, 10, 2, 1, 1)
        self.l49 = QtGui.QLabel(self.gridLayoutWidget)
        self.l49.setObjectName(_fromUtf8("l49"))
        self.gridLayout.addWidget(self.l49, 4, 9, 1, 1)
        self.l57 = QtGui.QLabel(self.gridLayoutWidget)
        self.l57.setObjectName(_fromUtf8("l57"))
        self.gridLayout.addWidget(self.l57, 5, 7, 1, 1)
        self.l25 = QtGui.QLabel(self.gridLayoutWidget)
        self.l25.setObjectName(_fromUtf8("l25"))
        self.gridLayout.addWidget(self.l25, 2, 5, 1, 1)
        self.l8 = QtGui.QLabel(self.gridLayoutWidget)
        self.l8.setObjectName(_fromUtf8("l8"))
        self.gridLayout.addWidget(self.l8, 0, 8, 1, 1)
        self.l45 = QtGui.QLabel(self.gridLayoutWidget)
        self.l45.setObjectName(_fromUtf8("l45"))
        self.gridLayout.addWidget(self.l45, 4, 5, 1, 1)
        self.l96 = QtGui.QLabel(self.gridLayoutWidget)
        self.l96.setObjectName(_fromUtf8("l96"))
        self.gridLayout.addWidget(self.l96, 9, 6, 1, 1)
        self.l106 = QtGui.QLabel(self.gridLayoutWidget)
        self.l106.setObjectName(_fromUtf8("l106"))
        self.gridLayout.addWidget(self.l106, 10, 6, 1, 1)
        self.l46 = QtGui.QLabel(self.gridLayoutWidget)
        self.l46.setObjectName(_fromUtf8("l46"))
        self.gridLayout.addWidget(self.l46, 4, 6, 1, 1)
        self.l77 = QtGui.QLabel(self.gridLayoutWidget)
        self.l77.setObjectName(_fromUtf8("l77"))
        self.gridLayout.addWidget(self.l77, 7, 7, 1, 1)
        self.l105 = QtGui.QLabel(self.gridLayoutWidget)
        self.l105.setObjectName(_fromUtf8("l105"))
        self.gridLayout.addWidget(self.l105, 10, 5, 1, 1)
        self.l91 = QtGui.QLabel(self.gridLayoutWidget)
        self.l91.setObjectName(_fromUtf8("l91"))
        self.gridLayout.addWidget(self.l91, 9, 1, 1, 1)
        self.l66 = QtGui.QLabel(self.gridLayoutWidget)
        self.l66.setObjectName(_fromUtf8("l66"))
        self.gridLayout.addWidget(self.l66, 6, 6, 1, 1)
        self.l104 = QtGui.QLabel(self.gridLayoutWidget)
        self.l104.setObjectName(_fromUtf8("l104"))
        self.gridLayout.addWidget(self.l104, 10, 4, 1, 1)
        self.l26 = QtGui.QLabel(self.gridLayoutWidget)
        self.l26.setObjectName(_fromUtf8("l26"))
        self.gridLayout.addWidget(self.l26, 2, 6, 1, 1)
        self.l7 = QtGui.QLabel(self.gridLayoutWidget)
        self.l7.setObjectName(_fromUtf8("l7"))
        self.gridLayout.addWidget(self.l7, 0, 7, 1, 1)
        self.l116 = QtGui.QLabel(self.gridLayoutWidget)
        self.l116.setObjectName(_fromUtf8("l116"))
        self.gridLayout.addWidget(self.l116, 11, 6, 1, 1)
        self.l6 = QtGui.QLabel(self.gridLayoutWidget)
        self.l6.setObjectName(_fromUtf8("l6"))
        self.gridLayout.addWidget(self.l6, 0, 6, 1, 1)
        self.l23 = QtGui.QLabel(self.gridLayoutWidget)
        self.l23.setObjectName(_fromUtf8("l23"))
        self.gridLayout.addWidget(self.l23, 2, 3, 1, 1)
        self.l58 = QtGui.QLabel(self.gridLayoutWidget)
        self.l58.setObjectName(_fromUtf8("l58"))
        self.gridLayout.addWidget(self.l58, 5, 8, 1, 1)
        self.l47 = QtGui.QLabel(self.gridLayoutWidget)
        self.l47.setObjectName(_fromUtf8("l47"))
        self.gridLayout.addWidget(self.l47, 4, 7, 1, 1)
        self.l76 = QtGui.QLabel(self.gridLayoutWidget)
        self.l76.setObjectName(_fromUtf8("l76"))
        self.gridLayout.addWidget(self.l76, 7, 6, 1, 1)
        self.l30 = QtGui.QLabel(self.gridLayoutWidget)
        self.l30.setObjectName(_fromUtf8("l30"))
        self.gridLayout.addWidget(self.l30, 3, 0, 1, 1)
        self.l95 = QtGui.QLabel(self.gridLayoutWidget)
        self.l95.setObjectName(_fromUtf8("l95"))
        self.gridLayout.addWidget(self.l95, 9, 5, 1, 1)
        self.l79 = QtGui.QLabel(self.gridLayoutWidget)
        self.l79.setObjectName(_fromUtf8("l79"))
        self.gridLayout.addWidget(self.l79, 7, 9, 1, 1)
        self.l56 = QtGui.QLabel(self.gridLayoutWidget)
        self.l56.setMargin(0)
        self.l56.setObjectName(_fromUtf8("l56"))
        self.gridLayout.addWidget(self.l56, 5, 6, 1, 1)
        self.l70 = QtGui.QLabel(self.gridLayoutWidget)
        self.l70.setObjectName(_fromUtf8("l70"))
        self.gridLayout.addWidget(self.l70, 7, 0, 1, 1)
        self.l87 = QtGui.QLabel(self.gridLayoutWidget)
        self.l87.setObjectName(_fromUtf8("l87"))
        self.gridLayout.addWidget(self.l87, 8, 7, 1, 1)
        self.l109 = QtGui.QLabel(self.gridLayoutWidget)
        self.l109.setObjectName(_fromUtf8("l109"))
        self.gridLayout.addWidget(self.l109, 10, 9, 1, 1)
        self.l89 = QtGui.QLabel(self.gridLayoutWidget)
        self.l89.setObjectName(_fromUtf8("l89"))
        self.gridLayout.addWidget(self.l89, 8, 9, 1, 1)
        self.l80 = QtGui.QLabel(self.gridLayoutWidget)
        self.l80.setObjectName(_fromUtf8("l80"))
        self.gridLayout.addWidget(self.l80, 8, 0, 1, 1)
        self.l118 = QtGui.QLabel(self.gridLayoutWidget)
        self.l118.setObjectName(_fromUtf8("l118"))
        self.gridLayout.addWidget(self.l118, 11, 8, 1, 1)
        self.l117 = QtGui.QLabel(self.gridLayoutWidget)
        self.l117.setObjectName(_fromUtf8("l117"))
        self.gridLayout.addWidget(self.l117, 11, 7, 1, 1)
        self.l10 = QtGui.QLabel(self.gridLayoutWidget)
        self.l10.setObjectName(_fromUtf8("l10"))
        self.gridLayout.addWidget(self.l10, 1, 0, 1, 1)
        self.l28 = QtGui.QLabel(self.gridLayoutWidget)
        self.l28.setObjectName(_fromUtf8("l28"))
        self.gridLayout.addWidget(self.l28, 2, 8, 1, 1)
        self.l20 = QtGui.QLabel(self.gridLayoutWidget)
        self.l20.setObjectName(_fromUtf8("l20"))
        self.gridLayout.addWidget(self.l20, 2, 0, 1, 1)
        self.l29 = QtGui.QLabel(self.gridLayoutWidget)
        self.l29.setObjectName(_fromUtf8("l29"))
        self.gridLayout.addWidget(self.l29, 2, 9, 1, 1)
        self.l97 = QtGui.QLabel(self.gridLayoutWidget)
        self.l97.setObjectName(_fromUtf8("l97"))
        self.gridLayout.addWidget(self.l97, 9, 7, 1, 1)
        self.l40 = QtGui.QLabel(self.gridLayoutWidget)
        self.l40.setObjectName(_fromUtf8("l40"))
        self.gridLayout.addWidget(self.l40, 4, 0, 1, 1)
        self.l98 = QtGui.QLabel(self.gridLayoutWidget)
        self.l98.setObjectName(_fromUtf8("l98"))
        self.gridLayout.addWidget(self.l98, 9, 8, 1, 1)
        self.l50 = QtGui.QLabel(self.gridLayoutWidget)
        self.l50.setObjectName(_fromUtf8("l50"))
        self.gridLayout.addWidget(self.l50, 5, 0, 1, 1)
        self.l27 = QtGui.QLabel(self.gridLayoutWidget)
        self.l27.setObjectName(_fromUtf8("l27"))
        self.gridLayout.addWidget(self.l27, 2, 7, 1, 1)
        self.l41 = QtGui.QLabel(self.gridLayoutWidget)
        self.l41.setObjectName(_fromUtf8("l41"))
        self.gridLayout.addWidget(self.l41, 4, 1, 1, 1)
        self.l51 = QtGui.QLabel(self.gridLayoutWidget)
        self.l51.setObjectName(_fromUtf8("l51"))
        self.gridLayout.addWidget(self.l51, 5, 1, 1, 1)
        self.l39 = QtGui.QLabel(self.gridLayoutWidget)
        self.l39.setObjectName(_fromUtf8("l39"))
        self.gridLayout.addWidget(self.l39, 3, 9, 1, 1)
        self.l99 = QtGui.QLabel(self.gridLayoutWidget)
        self.l99.setObjectName(_fromUtf8("l99"))
        self.gridLayout.addWidget(self.l99, 9, 9, 1, 1)
        self.l60 = QtGui.QLabel(self.gridLayoutWidget)
        self.l60.setObjectName(_fromUtf8("l60"))
        self.gridLayout.addWidget(self.l60, 6, 0, 1, 1)
        self.l68 = QtGui.QLabel(self.gridLayoutWidget)
        self.l68.setObjectName(_fromUtf8("l68"))
        self.gridLayout.addWidget(self.l68, 6, 8, 1, 1)
        self.l69 = QtGui.QLabel(self.gridLayoutWidget)
        self.l69.setObjectName(_fromUtf8("l69"))
        self.gridLayout.addWidget(self.l69, 6, 9, 1, 1)
        self.l107 = QtGui.QLabel(self.gridLayoutWidget)
        self.l107.setObjectName(_fromUtf8("l107"))
        self.gridLayout.addWidget(self.l107, 10, 7, 1, 1)
        self.l94 = QtGui.QLabel(self.gridLayoutWidget)
        self.l94.setObjectName(_fromUtf8("l94"))
        self.gridLayout.addWidget(self.l94, 9, 4, 1, 1)
        self.l85 = QtGui.QLabel(self.gridLayoutWidget)
        self.l85.setObjectName(_fromUtf8("l85"))
        self.gridLayout.addWidget(self.l85, 8, 5, 1, 1)
        self.l88 = QtGui.QLabel(self.gridLayoutWidget)
        self.l88.setObjectName(_fromUtf8("l88"))
        self.gridLayout.addWidget(self.l88, 8, 8, 1, 1)
        self.l108 = QtGui.QLabel(self.gridLayoutWidget)
        self.l108.setObjectName(_fromUtf8("l108"))
        self.gridLayout.addWidget(self.l108, 10, 8, 1, 1)
        self.l43 = QtGui.QLabel(self.gridLayoutWidget)
        self.l43.setObjectName(_fromUtf8("l43"))
        self.gridLayout.addWidget(self.l43, 4, 3, 1, 1)
        self.l84 = QtGui.QLabel(self.gridLayoutWidget)
        self.l84.setObjectName(_fromUtf8("l84"))
        self.gridLayout.addWidget(self.l84, 8, 4, 1, 1)
        self.l42 = QtGui.QLabel(self.gridLayoutWidget)
        self.l42.setObjectName(_fromUtf8("l42"))
        self.gridLayout.addWidget(self.l42, 4, 2, 1, 1)
        self.l64 = QtGui.QLabel(self.gridLayoutWidget)
        self.l64.setObjectName(_fromUtf8("l64"))
        self.gridLayout.addWidget(self.l64, 6, 4, 1, 1)
        self.l52 = QtGui.QLabel(self.gridLayoutWidget)
        self.l52.setObjectName(_fromUtf8("l52"))
        self.gridLayout.addWidget(self.l52, 5, 2, 1, 1)
        self.l62 = QtGui.QLabel(self.gridLayoutWidget)
        self.l62.setObjectName(_fromUtf8("l62"))
        self.gridLayout.addWidget(self.l62, 6, 2, 1, 1)
        self.l32 = QtGui.QLabel(self.gridLayoutWidget)
        self.l32.setObjectName(_fromUtf8("l32"))
        self.gridLayout.addWidget(self.l32, 3, 2, 1, 1)
        self.l22 = QtGui.QLabel(self.gridLayoutWidget)
        self.l22.setObjectName(_fromUtf8("l22"))
        self.gridLayout.addWidget(self.l22, 2, 2, 1, 1)
        self.l12 = QtGui.QLabel(self.gridLayoutWidget)
        self.l12.setObjectName(_fromUtf8("l12"))
        self.gridLayout.addWidget(self.l12, 1, 2, 1, 1)
        self.l92 = QtGui.QLabel(self.gridLayoutWidget)
        self.l92.setObjectName(_fromUtf8("l92"))
        self.gridLayout.addWidget(self.l92, 9, 2, 1, 1)
        self.l2 = QtGui.QLabel(self.gridLayoutWidget)
        self.l2.setObjectName(_fromUtf8("l2"))
        self.gridLayout.addWidget(self.l2, 0, 2, 1, 1)
        self.l63 = QtGui.QLabel(self.gridLayoutWidget)
        self.l63.setObjectName(_fromUtf8("l63"))
        self.gridLayout.addWidget(self.l63, 6, 3, 1, 1)
        self.l65 = QtGui.QLabel(self.gridLayoutWidget)
        self.l65.setObjectName(_fromUtf8("l65"))
        self.gridLayout.addWidget(self.l65, 6, 5, 1, 1)
        self.l1 = QtGui.QLabel(self.gridLayoutWidget)
        self.l1.setObjectName(_fromUtf8("l1"))
        self.gridLayout.addWidget(self.l1, 0, 1, 1, 1)
        self.l3 = QtGui.QLabel(self.gridLayoutWidget)
        self.l3.setObjectName(_fromUtf8("l3"))
        self.gridLayout.addWidget(self.l3, 0, 3, 1, 1)
        self.l4 = QtGui.QLabel(self.gridLayoutWidget)
        self.l4.setObjectName(_fromUtf8("l4"))
        self.gridLayout.addWidget(self.l4, 0, 4, 1, 1)
        self.l5 = QtGui.QLabel(self.gridLayoutWidget)
        self.l5.setObjectName(_fromUtf8("l5"))
        self.gridLayout.addWidget(self.l5, 0, 5, 1, 1)
        self.l15 = QtGui.QLabel(self.gridLayoutWidget)
        self.l15.setObjectName(_fromUtf8("l15"))
        self.gridLayout.addWidget(self.l15, 1, 5, 1, 1)
        self.l11 = QtGui.QLabel(self.gridLayoutWidget)
        self.l11.setObjectName(_fromUtf8("l11"))
        self.gridLayout.addWidget(self.l11, 1, 1, 1, 1)
        self.l13 = QtGui.QLabel(self.gridLayoutWidget)
        self.l13.setObjectName(_fromUtf8("l13"))
        self.gridLayout.addWidget(self.l13, 1, 3, 1, 1)
        self.l14 = QtGui.QLabel(self.gridLayoutWidget)
        self.l14.setObjectName(_fromUtf8("l14"))
        self.gridLayout.addWidget(self.l14, 1, 4, 1, 1)
        self.l21 = QtGui.QLabel(self.gridLayoutWidget)
        self.l21.setObjectName(_fromUtf8("l21"))
        self.gridLayout.addWidget(self.l21, 2, 1, 1, 1)
        self.l31 = QtGui.QLabel(self.gridLayoutWidget)
        self.l31.setObjectName(_fromUtf8("l31"))
        self.gridLayout.addWidget(self.l31, 3, 1, 1, 1)
        self.l37 = QtGui.QLabel(self.gridLayoutWidget)
        self.l37.setObjectName(_fromUtf8("l37"))
        self.gridLayout.addWidget(self.l37, 3, 7, 1, 1)
        self.l17 = QtGui.QLabel(self.gridLayoutWidget)
        self.l17.setObjectName(_fromUtf8("l17"))
        self.gridLayout.addWidget(self.l17, 1, 7, 1, 1)
        self.l16 = QtGui.QLabel(self.gridLayoutWidget)
        self.l16.setObjectName(_fromUtf8("l16"))
        self.gridLayout.addWidget(self.l16, 1, 6, 1, 1)
        self.l103 = QtGui.QLabel(self.gridLayoutWidget)
        self.l103.setObjectName(_fromUtf8("l103"))
        self.gridLayout.addWidget(self.l103, 10, 3, 1, 1)
        self.l33 = QtGui.QLabel(self.gridLayoutWidget)
        self.l33.setObjectName(_fromUtf8("l33"))
        self.gridLayout.addWidget(self.l33, 3, 3, 1, 1)
        self.l48 = QtGui.QLabel(self.gridLayoutWidget)
        self.l48.setObjectName(_fromUtf8("l48"))
        self.gridLayout.addWidget(self.l48, 4, 8, 1, 1)
        self.l90 = QtGui.QLabel(self.gridLayoutWidget)
        self.l90.setObjectName(_fromUtf8("l90"))
        self.gridLayout.addWidget(self.l90, 9, 0, 1, 1)
        self.l18 = QtGui.QLabel(self.gridLayoutWidget)
        self.l18.setObjectName(_fromUtf8("l18"))
        self.gridLayout.addWidget(self.l18, 1, 8, 1, 1)
        self.l0 = QtGui.QLabel(self.gridLayoutWidget)
        self.l0.setObjectName(_fromUtf8("l0"))
        self.gridLayout.addWidget(self.l0, 0, 0, 1, 1)
        self.l38 = QtGui.QLabel(self.gridLayoutWidget)
        self.l38.setObjectName(_fromUtf8("l38"))
        self.gridLayout.addWidget(self.l38, 3, 8, 1, 1)
        self.l36 = QtGui.QLabel(self.gridLayoutWidget)
        self.l36.setObjectName(_fromUtf8("l36"))
        self.gridLayout.addWidget(self.l36, 3, 6, 1, 1)
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(400, 210, 121, 31))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_17 = QtGui.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(400, 90, 121, 31))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_20 = QtGui.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(400, 240, 101, 81))
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(400, 120, 121, 81))
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_21.setObjectName(_fromUtf8("label_21"))

        self.bottone = QtGui.QPushButton(Dialog)
        self.bottone.setGeometry(QtCore.QRect(240, 390, 61, 31))
        self.bottone.setObjectName(_fromUtf8("bottone"))
        self.bottone.setText("Move")

        self.comboBox = QtGui.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(140, 390, 61, 31))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))

        self.retranslateUi(Dialog, tabella)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.setStyleLabel()

    def retranslateUi(self, Dialog, tabella):
        Dialog.setWindowTitle(_translate("Dialog", "Chess Promotion Game", None))
        self.l19.setText(_translate("Dialog", "19", None))
        self.l54.setText(_translate("Dialog", "54", None))
        self.l112.setText(_translate("Dialog", "112", None))
        self.l101.setText(_translate("Dialog", "101", None))
        self.l67.setText(_translate("Dialog", "67", None))
        self.l113.setText(_translate("Dialog", "113", None))
        self.l111.setText(_translate("Dialog", "111", None))
        self.l59.setText(_translate("Dialog", "59", None))
        self.l9.setText(_translate("Dialog", "9", None))
        self.l34.setText(_translate("Dialog", "34", None))
        self.l44.setText(_translate("Dialog", "44", None))
        self.l72.setText(_translate("Dialog", "72", None))
        self.l114.setText(_translate("Dialog", "114", None))
        self.l55.setText(_translate("Dialog", "55", None))
        self.l75.setText(_translate("Dialog", "75", None))
        self.l35.setText(_translate("Dialog", "35", None))
        self.l93.setText(_translate("Dialog", "93", None))
        self.l24.setText(_translate("Dialog", "24", None))
        self.l74.setText(_translate("Dialog", "74", None))
        self.l78.setText(_translate("Dialog", "78", None))
        self.l86.setText(_translate("Dialog", "86", None))
        self.l71.setText(_translate("Dialog", "71", None))
        self.l61.setText(_translate("Dialog", "61", None))
        self.l110.setText(_translate("Dialog", "110", None))
        self.l73.setText(_translate("Dialog", "73", None))
        self.l100.setText(_translate("Dialog", "100", None))
        self.l81.setText(_translate("Dialog", "81", None))
        self.l83.setText(_translate("Dialog", "83", None))
        self.l53.setText(_translate("Dialog", "53", None))
        self.l82.setText(_translate("Dialog", "82", None))
        self.l102.setText(_translate("Dialog", "102", None))
        self.l49.setText(_translate("Dialog", "49", None))
        self.l57.setText(_translate("Dialog", "57", None))
        self.l25.setText(_translate("Dialog", "25", None))
        self.l8.setText(_translate("Dialog", "8", None))
        self.l45.setText(_translate("Dialog", "45", None))
        self.l96.setText(_translate("Dialog", "96", None))
        self.l106.setText(_translate("Dialog", "106", None))
        self.l46.setText(_translate("Dialog", "46", None))
        self.l77.setText(_translate("Dialog", "77", None))
        self.l105.setText(_translate("Dialog", "105", None))
        self.l91.setText(_translate("Dialog", "91", None))
        self.l66.setText(_translate("Dialog", "66", None))
        self.l104.setText(_translate("Dialog", "104", None))
        self.l26.setText(_translate("Dialog", "26", None))
        self.l7.setText(_translate("Dialog", "7", None))
        self.l116.setText(_translate("Dialog", "116", None))
        self.l6.setText(_translate("Dialog", "6", None))
        self.l23.setText(_translate("Dialog", "23", None))
        self.l58.setText(_translate("Dialog", "58", None))
        self.l47.setText(_translate("Dialog", "47", None))
        self.l76.setText(_translate("Dialog", "76", None))
        self.l30.setText(_translate("Dialog", "30", None))
        self.l95.setText(_translate("Dialog", "95", None))
        self.l79.setText(_translate("Dialog", "79", None))
        self.l56.setText(_translate("Dialog", "56", None))
        self.l70.setText(_translate("Dialog", "70", None))
        self.l87.setText(_translate("Dialog", "87", None))
        self.l115.setText(_translate("Dialog", "115", None))
        self.l109.setText(_translate("Dialog", "109", None))
        self.l119.setText(_translate("Dialog", "119", None))
        self.l80.setText(_translate("Dialog", "80", None))
        self.l89.setText(_translate("Dialog", "89", None))
        self.l118.setText(_translate("Dialog", "118", None))
        self.l117.setText(_translate("Dialog", "117", None))
        self.l10.setText(_translate("Dialog", "10", None))
        self.l28.setText(_translate("Dialog", "28", None))
        self.l20.setText(_translate("Dialog", "20", None))
        self.l29.setText(_translate("Dialog", "29", None))
        self.l97.setText(_translate("Dialog", "97", None))
        self.l40.setText(_translate("Dialog", "40", None))
        self.l98.setText(_translate("Dialog", "98", None))
        self.l50.setText(_translate("Dialog", "50", None))
        self.l27.setText(_translate("Dialog", "27", None))
        self.l41.setText(_translate("Dialog", "41", None))
        self.l51.setText(_translate("Dialog", "51", None))
        self.l39.setText(_translate("Dialog", "39", None))
        self.l99.setText(_translate("Dialog", "99", None))
        self.l60.setText(_translate("Dialog", "60", None))
        self.l68.setText(_translate("Dialog", "68", None))
        self.l69.setText(_translate("Dialog", "69", None))
        self.l107.setText(_translate("Dialog", "107", None))
        self.l94.setText(_translate("Dialog", "94", None))
        self.l85.setText(_translate("Dialog", "85", None))
        self.l88.setText(_translate("Dialog", "88", None))
        self.l108.setText(_translate("Dialog", "108", None))
        self.l43.setText(_translate("Dialog", "43", None))
        self.l84.setText(_translate("Dialog", "84", None))
        self.l42.setText(_translate("Dialog", "42", None))
        self.l64.setText(_translate("Dialog", "64", None))
        self.l52.setText(_translate("Dialog", "52", None))
        self.l62.setText(_translate("Dialog", "62", None))
        self.l32.setText(_translate("Dialog", "32", None))
        self.l22.setText(_translate("Dialog", "22", None))
        self.l12.setText(_translate("Dialog", "12", None))
        self.l92.setText(_translate("Dialog", "92", None))
        self.l2.setText(_translate("Dialog", "2", None))
        self.l63.setText(_translate("Dialog", "63", None))
        self.l65.setText(_translate("Dialog", "65", None))
        self.l1.setText(_translate("Dialog", "1", None))
        self.l3.setText(_translate("Dialog", "3", None))
        self.l4.setText(_translate("Dialog", "4", None))
        self.l5.setText(_translate("Dialog", "5", None))
        self.l15.setText(_translate("Dialog", "15", None))
        self.l11.setText(_translate("Dialog", "11", None))
        self.l13.setText(_translate("Dialog", "13", None))
        self.l14.setText(_translate("Dialog", "14", None))
        self.l21.setText(_translate("Dialog", "21", None))
        self.l31.setText(_translate("Dialog", "31", None))
        self.l37.setText(_translate("Dialog", "37", None))
        self.l17.setText(_translate("Dialog", "17", None))
        self.l16.setText(_translate("Dialog", "16", None))
        self.l103.setText(_translate("Dialog", "103", None))
        self.l33.setText(_translate("Dialog", "33", None))
        self.l48.setText(_translate("Dialog", "48", None))
        self.l90.setText(_translate("Dialog", "90", None))
        self.l18.setText(_translate("Dialog", "18", None))
        self.l0.setText(_translate("Dialog", "0", None))
        self.l38.setText(_translate("Dialog", "38", None))
        self.l36.setText(_translate("Dialog", "36", None))
        self.label.setText(_translate("Dialog", "PLAYER Statistics:", None))
        self.label_17.setText(_translate("Dialog", "CPU Statistics:", None))
        self.label_20.setText(_translate("Dialog", "8 pawns", None))
        self.label_21.setText(_translate("Dialog", "8 pawns", None))
        #self.colora(tabella)

    def colora(self, t,dadove=None):
        for i, p in enumerate(t.board):
            stringa_posizione = "l%d" % i
            label_posizione = self.gridLayoutWidget.findChild(QtGui.QLabel, stringa_posizione)
            label_posizione.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
            label_posizione.setText(p)
            img = None
            if p == 'P':
                img = QtGui.QPixmap("./ChessImages/pawn-black16.png")
            if p == 'p':
                img = QtGui.QPixmap("./ChessImages/pawn-white16.png")
            if p == 'K':
                img = QtGui.QPixmap("./ChessImages/king-black16.png")
            if p == 'k':
                img = QtGui.QPixmap("./ChessImages/king-white16.png")
            if img is not None:
                label_posizione.setPixmap(img)
        self.setStyleLabel()

    # setta i colori della scacchiera e imposta le letter A - H e i numeri 1 - 8 per le coordinate
    def setStyleLabel(self):
        for riga in range(2,10):
            for colonna in range(1,9):
                stringa_posizione = "l%d%d" % (riga, colonna)
                l = self.gridLayoutWidget.findChild(QtGui.QLabel, stringa_posizione)
                l.setStyleSheet("QLabel { color: rgb(0, 0, 0); font-size: 11px; background-color: rgb(255, 255, 255); border: 1px solid rgb(0, 0, 0); }")
        self.l101.setText("A")
        self.l101.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.l102.setText("B")
        self.l102.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.l103.setText("C")
        self.l103.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.l104.setText("D")
        self.l104.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.l105.setText("E")
        self.l105.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.l106.setText("F")
        self.l106.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.l107.setText("G")
        self.l107.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.l108.setText("H")
        self.l108.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.l90.setText("1")
        self.l80.setText("2")
        self.l70.setText("3")
        self.l60.setText("4")
        self.l50.setText("5")
        self.l40.setText("6")
        self.l30.setText("7")
        self.l20.setText("8")
